 name: Elixir CI

 on:
   pull_request:
     branches: [ master ]

 jobs:
   build:
     name: Lint and Test
     runs-on: ubuntu-latest

     services:
       postgres:
         image: postgres
         env:
           POSTGRES_USER: user
           POSTGRES_PASSWORD: password
           POSTGRES_DB: project_42
         ports:
           - 5432:5432
         options: >-
           --health-cmd pg_isready
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5

     steps:
     - uses: actions/checkout@v4

     - name: Set up Elixir
       uses: erlef/setup-beam@v1
       with:
         elixir-version: '1.18.3'
         otp-version: '28.0'

     - name: Restore dependencies cache
       uses: actions/cache@v4
       with:
         path: deps
         key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
         restore-keys: ${{ runner.os }}-mix-

     - name: Restore build cache
       uses: actions/cache@v4
       with:
         path: _build
         key: ${{ runner.os }}-build-${{ hashFiles('**/mix.lock') }}
         restore-keys: ${{ runner.os }}-build-

     - name: Install dependencies
       run: mix deps.get

     - name: Check formatting
       run: mix format --check-formatted

     - name: Run Credo
       run: mix credo

     - name: Run tests
       run: mix test
       env:
         MIX_ENV: test
